### ISSUE TITLE
Glitch in basisAnnotate when id_type is "SYMBOL"

### ISSUE THREAD

**Issue by aepstein96** [JSB-UCLA/scPNMF#2]
Hello,

When running the basisAnnotate function on a test dataset ([Seurat's test dataset](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html)), I noticed that the function fails when using id_type = "SYMBOL" with the following error:

```
Error in names(x) <- value : 'names' attribute [2] must be the same length as the vector [1]
```

It seems this error occurs because in the clusterProfiler::compareCluster function, "readable" must be set to FALSE if keyType="SYMBOL". I was able to fix the issue by modifying the basisAnnotate function code to set "readable=FALSE". 

Best,
Alex

**Comment by aileenlikexin** [comment]
Hi Alex, 

Thank you for pointing this out! We will fix this issue soon.


Best,
Kexin
